version: '3'

volumes:
  testproject_1_local_postgres_data: {}
  testproject_1_local_postgres_data_backups: {}

services:
  django:
    &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: testproject_1_local_django
    container_name: testproject_1_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: testproject_1_production_postgres
    container_name: testproject_1_local_postgres
    volumes:
      - testproject_1_local_postgres_data:/var/lib/postgresql/data
      - testproject_1_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:5.0

  celery:
    <<: *django
    container_name: celeryworker
    ports:
      - "49483:49483"
    command: /start-celeryworker
    depends_on:
      - redis

  celerybeat:
    <<: *django
    container_name: celerybeat
    ports:
      - "49484:49484"
    command: /start-celerybeat

  flower:
    <<: *django
    container_name: celeryflower
    ports:
      - "49485:49485"
    command: /start-flower
    depends_on:
      - redis

  # docs:
  #   image: testproject_1_local_docs
  #   container_name: testproject_1_local_docs
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./testproject_1:/app/testproject_1:z
  #   ports:
  #     - "9000:9000"
  #   command: /start-docs
