version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}

networks:
  my_custom_network:
    external: true
        
services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: testproject_1_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    # ports:
    #   - "8000"
    command: /start
    networks:
      - my_custom_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: testproject_1_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - my_custom_network

  redis:
    image: redis:6
    networks:
      - my_custom_network
